api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcremovemfaPOST
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'POST'
    port: 0
    rewrite: /api/v1/mfaconfig/remove
    type: exact
    url: /mahindrwrapperapisrvc/mfaconfig/remove
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcpasswordpolicysave
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'POST'
    port: 0
    rewrite: /api/v1/passwordpolicy/save
    type: exact
    url: /mahindrwrapperapisrvc/passwordpolicy/save
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcpasswordpolicy
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'GET'
    port: 0
    rewrite: /api/v1/passwordpolicy/
    type: exact
    url: /mahindrwrapperapisrvc/passwordpolicy/
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcpasswordpolicyupdate
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'POST'
    port: 0
    rewrite: /api/v1/passwordpolicy/update/
    type: exact
    url: /mahindrwrapperapisrvc/passwordpolicy/update/
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcpasswordpolicysearch
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'GET'
    port: 0
    rewrite: /api/v1/passwordpolicy/search
    type: exact
    url: /mahindrwrapperapisrvc/passwordpolicy/search
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcpasswordpolicypaswordchangedrule
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'GET'
    port: 0
    rewrite: /api/v1/passwordpolicy/paswordchangedrule/
    type: exact
    url: /mahindrwrapperapisrvc/passwordpolicy/paswordchangedrule/
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcpasswordpolicysavepasswordcompositionrule
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'POST'
    port: 0
    rewrite: /api/v1/passwordpolicy/savepasswordcompositionrule/
    type: exact
    url: /mahindrwrapperapisrvc/passwordpolicy/savepasswordcompositionrule/
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcresetpassword
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'POST'
    port: 0
    rewrite: /api/v1/resetpassword/
    type: exact
    url: /mahindrwrapperapisrvc/resetpassword/
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcrevokesession
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'GET'
    port: 0
    rewrite: /api/v1/revokesession/
    type: exact
    url: /mahindrwrapperapisrvc/revokesession/
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
api: /v1/config/projects/{project}/routing/ingress/{id}
meta:
  id: mahindrwrapperapisrvcunlockuser
  project: unotech
spec:
  modify:
    headers: []
    outputFormat: yaml
    requestTemplate: ""
    responseTemplate: ""
    template: go
  project: unotech
  rule:
    rule: allow
  source:
    hosts:
      - '*'
    methods:
      - 'POST'
    port: 0
    rewrite: /api/v1/unlockuser/
    type: exact
    url: /mahindrwrapperapisrvc/unlockuser/
  targets:
    - host: mahindrwrapperapisrvc.unotech.svc.cluster.local
      port: 8080
      scheme: http
      type: ""
      version: ""
      weight: 100
type: ingress-route
---
